export const FN_GET_SETTING = "function getSetting() view returns ((address token, address patron, address nft, uint256 nftId, address prizeNft, uint256 prizeNftId, uint256 minAmount, uint256 initPrize, uint256 startTime, uint256 endTime, uint32 interval, uint16 betPerc, uint16 refPerc, uint16 winnerPerc, uint16 nextsPerc, uint16 patronPerc, uint16 holdersPerc, uint16 teamPerc, uint16 foundationPerc, uint16 maxNexts, uint16 maxHolders, bool autoFinalize, bool poolBalReq, bool isFixedPrize, string uri))"
export const FN_GET_CONFIG = "function getConfig() view returns ((address factory, address team, address foundation, address nextVault, address holdersVault, address nftWinner, address lastBettor, uint256 totalBets, uint256 nextBetAt, bool isFinalized))"
export const FN_GET_PRIZE = "function getPrize() view returns ((uint256 prizePool, uint256 winner, uint256 nexts, uint256 patron, uint256 holders, uint256 team, uint256 foundation, uint256 next, uint256 holder))"
export const FN_GET_FINAL_PRIZE = "function getFinalPrize() view returns ((uint256 prizePool, uint256 winner, uint256 nexts, uint256 patron, uint256 holders, uint256 team, uint256 foundation, uint256 next, uint256 holder))"
export const FN_GET_POSITIONS = "function getPositions() view returns (address[])"
export const FN_GET_BET_AMOUNT = "function getBetAmount() view returns (uint256)"
export const FN_GET_HOLDERS = "function getHolders() view returns (address[])"
export const FN_GET_RANDOM_HOLDERS = "function getRandomHolders() view returns (address[])"
export const FN_GET_EARNERS = "function getEarners() view returns (address[], uint256[], uint256[], uint256[])"
export const FN_GET_TIMESTAMPS = "function getTimestamps() view returns (uint256, uint256, uint256, uint256, uint256)"
export const FN_IS_GAME_ACTIVE = "function isGameActive() view returns (bool)"
export const FN_HAS_PRIZE_NFT = "function hasPrizeNft() view returns (bool)"
export const FN_USDT_BALANCE = "function usdtBalance() view returns (uint256)"

export const EV_PLACED_BET = "event PlacedBet(uint256 indexed betId, address indexed bettor, uint256 indexed amount, address token, uint256 timestamp)"